apiVersion: v1
kind: Pod
metadata:
  name: blocked-client
  namespace: security-lab
spec:
  containers:
  - name: box
    image: busybox
    command: ["sleep","3600"]
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"

