apiVersion: v1
kind: PersistentVolume
metadata:
  name: lab-pv
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/lab-data"
  persistentVolumeReclaimPolicy: Retain
