apiVersion: v1
kind: Service
metadata:
  name: nginx-production
  labels:
    app: nginx
    environment: production
  annotations:
    description: "Production-facing nginx service"
spec:
  type: LoadBalancer
  sessionAffinity: ClientIP
  selector:
    app: nginx
  ports:
  - name: http
    port: 80
    targetPort: 80

